#!/bin/bash
# Quick Deploy with Ngrok

echo "========================================"
echo "  SkillCode GPT - Quick Deploy Setup"
echo "========================================"
echo ""
echo "Step 1: Download ngrok"
echo "Visit: https://ngrok.com/download"
echo "Download the Windows version (ZIP file)"
echo ""
echo "Step 2: Extract ngrok.exe to this folder"
echo ""
echo "Step 3: Sign up for ngrok (free)"
echo "Visit: https://dashboard.ngrok.com/signup"
echo ""
echo "Step 4: Get your authtoken"
echo "After signing up, copy your authtoken from:"
echo "https://dashboard.ngrok.com/get-started/your-authtoken"
echo ""
echo "Step 5: Run these commands:"
echo ""
echo "  ngrok config add-authtoken YOUR_TOKEN_HERE"
echo "  python app.py"
echo ""
echo "Step 6: In another terminal:"
echo "  ngrok http 5000"
echo ""
echo "You'll get a public URL!"
echo "========================================"
